name: Django CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests 
      env:
        DJANGO_SETTINGS_MODULE: projet_final.settings.base
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        pytest --cov=brefboard --cov-report=term --cov-fail-under=80
