name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libportaudio2 libportaudiocpp0 portaudio19-dev gcc ffmpeg
    - name: Install Python dependencies
      working-directory: ./projet_final
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      working-directory: ./projet_final
      env:
          DJANGO_TEST_MODE: 'True'
          DJANGO_SETTINGS_MODULE: projet_final.settings.production
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py test BrefBoard --exclude-tag=skip_whisper

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./projet_final
        file: ./projet_final/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/brefboard:${{ github.sha }}